services:
  app:
    image: rextra/rextra-backend-dev:${IMAGE_TAG:-latest}
    container_name: rextra-backend-dev
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - ./.env.dev
    networks:
      - rextra-net

  db:
    image: postgres:16
    container_name: rextra-backend-db-dev
    env_file:
      - ./.env.dev
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - rextra-net

volumes:
  db-data:

networks:
  rextra-net:
    external: true
