services:
  app:
    image: rextra/rextra-backend-dev:${IMAGE_TAG:-latest}
    depends_on:
      - db
    env_file:
      - ./.env.dev
    networks:
      - app-dev-network

  db:
    image: postgres:16
    env_file:
      - ./.env.dev
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - app-dev-network

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:-rextra-backend}-nginx-dev
    volumes:
      - .:/var/www/html
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT:-81}:80
    depends_on:
      - app
    networks:
      - app-dev-network

volumes:
  db-data:

networks:
  app-dev-network:
    driver: bridge
